import { ReactNode } from "react";
import type { Metadata } from "next";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const poppins : NextFontWithVariable = Poppins({ 
  subsets: ["latin"], 
  variable: "--font-poppins",
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children } : 
  Readonly<{ children: ReactNode; }>) {
  
  return (
    <html lang="en">
      <body className={`${poppins.className} ${poppins.variable}}`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
